menu:
  Home: /
  Archives: /archives
  Github: https://github.com/phillychi3

headerimage: https://cdn.discordapp.com/attachments/927960120116260864/931775142298812467/333580.jpg?ex=65a21939&is=658fa439&hm=e35272ad8102d47b3a027e2a46b0b02a5d82a52b200e864ea803357faa9b20f2&
background: 'https://i.waifu.pics/38QXoHc.jpeg'

infocard:
  author: 白雲
  introduce: 建設中...
  links:
    - icon: fa-brands fa-github fa-xl
      link: "https://github.com/phillychi3"
    - icon: fa-brands fa-twitter fa-xl
      link: "https://x.com/philly030"
    - icon: fa-brands fa-instagram fa-xl
      link: "https://www.instagram.com/phillychi3/"

customize:
  test1:
    type: text
    text: '123'
  test2":
    type: image
    image: 'https://nekos.best/api/v2/neko/ae8ca777-d7f6-400f-8600-69702ae26672.png'
    url: '/'
  test3":
    type: image
    image: 'https://nekos.best/api/v2/neko/be1bef84-1789-40ec-b67d-a9287b82dc39.png'
    url: '/'


waline:
  enable: true
  serverurl: https://blog-waline-ten-ivory.vercel.app/
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  lang: zh-TW
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
  login: disable
  imageUploader: true
  commentCount: true
  pageSize: 10
  wordLimit: 0

GAnalytics:
  enable: true
  id: G-XV0QDHZQQ5