menu:
  Home: /
  Archives: /archives

headerimage: edit me
background: edit me

startyear: 2024

infocard:
  author: you name
  introduce: edit me
  links:
    - icon: fa-brands fa-github fa-xl
      link: https://github.com/phillychi3

customize:
  test1:
    type: text
    text: example
  test2":
    type: image
    image: https://nekos.best/api/v2/neko/ae8ca777-d7f6-400f-8600-69702ae26672.png
    url: https://www.google.com


waline:
  enable: false
  serverurl:
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  lang: zh-TW
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
  login: disable
  imageUploader: true
  commentCount: true
  pageSize: 10
  wordLimit: 0

GAnalytics:
  enable: false
  id: